### ISSUE TITLE
Version 8 - cant connect to Strava -  7.3 was fine!

### ISSUE THREAD

**Issue by Brucea72** [roznet/connectstats#106]
After the release of V8 ConnectStats app can no longer sync with Strava… v 7.3 worked fine. Remove and reinstall of app does not resolve.

error displayed as below when the app tries to launch the sign into Strava. 

{"message":"Bad Request","errors":[{"resource":"Application","field":"client_id","code":"invalid"}]}

**Comment by roznet** [comment]
yes, some people reported that, but in my testing it works.

I re-enabled bug report for version 8, do you mind to send me a bug report so I can try to understand where the problem comes from?

**Comment by Brucea72** [comment]
done that - many thanks for the quick response! - Just wanted to say been using the app for a while now and find it a brilliant companion for Strava!! - You could absolutely charge users to access it!! - Many thanks Bruce

**Comment by Brucea72** [comment]
Fixed syncing with Strava once more! Fantastic
