### ISSUE TITLE
Fit File Explorer not opening on Sonoma

### ISSUE THREAD

**Issue by bilak** [roznet/connectstats#108]
Hey, 
I've just installed FitFileExplorer from the appstore, however it's not opening on macos sonoma. 
If you need some debug/other info please let me know how to do it and I will post.

Thanks

**Comment by roznet** [comment]
Hi,
I could start it on Sonoma, do you see any error message? Does the menu not change to Fit File Explorer?

**Comment by bilak** [comment]
It doesn't even open for me so no error/nothing.

**Comment by bilak** [comment]
Ah it works! I just didn't seen the menu so it confused me. Maybe it would be nice to just open some popup on start so user knows that something has started.
