### ISSUE TITLE
The App is hangiing by „analyzing May“

### ISSUE THREAD

**Issue by 3Dscrewer** [roznet/connectstats#21]
I am using GC and AW3 as well, in Health all Data are free for CS.
Starting up, CS is connecting to Garmin and DL and ended up with a circling „analyzing May“.
The Phone is getting hot and switching the app to background and back to front is causing that the sign for analyzing is stopping.

**Comment by 3Dscrewer** [comment]
I have bought it a couple of time ago and it updates automatically if a new one comes.
I have also deleted and new installed.

**Comment by roznet** [comment]
ok, can you send me a bug report from the app, may help see what is happening. (in the config tab)
