### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by paulrbarnard** [roznet/connectstats#68]
I was looking for some insight into the use of your framework fit-sdk-swift so grabbed a copy of ConnectStats to take a look.  Unfortunately it won't build on my system.

On both the ConnectStats and FitFileExplore targets I get a build error 
.../ConnectStats/FitFileExplorer/src/GarminDataInterpreter.swift:29:8: No such module ‘GenericJSON’
.../CrossPlatform/ConnectStats/FitFileExplorer/src/FITFitFieldMap.swift:29:8: No such module 'GenericJSON'

There is no GenericJSON file in the repo nor a GenericJSON framework.

I guessed this might be the zoul generic-json-swift project from GitHub.  I cloned that project but it does not have GenericJSON files either just JSON.

I would be exceptionally grateful if you could point me in the right direction.

**Comment by roznet** [comment]
You need to do a 'pod install'

to install all the dependencies.

**Comment by paulrbarnard** [comment]
Brice,

I did.

Paul

**Comment by roznet** [comment]
Hum, any error when you did the pod install? Did it create the Pods directory with all the subdirectories in it?

**Comment by paulrbarnard** [comment]
Fortunately i didn’t close the terminal.  Also the Pods folder is created and there is a GenericJSON folder but it doesn’t contain a GenericJSON file...

pbarnard@Office-Mac-Pro-3 ConnectStats % pod install
Analyzing dependencies
Cloning spec repo `cocoapods` from `https://github.com/CocoaPods/Specs.git`
Downloading dependencies
Installing Flurry-iOS-SDK (10.1.0)
Installing GenericJSON (2.0.1)
Installing GoogleMaps (3.7.0)
Installing KeychainSwift (18.0.0)
Generating Pods project
Integrating client project
Pod installation complete! There are 4 dependencies from the Podfile and 4 total pods installed.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `ConnectStatsTestApp` to `Pods/Target Support Files/Pods-ConnectStatsTestApp/Pods-ConnectStatsTestApp.release.xcconfig` or include the `Pods/Target Support Files/Pods-ConnectStatsTestApp/Pods-ConnectStatsTestApp.release.xcconfig` in your build configuration (`connectstatstestapp/ConnectStatsTestApp.debug.xcconfig`).
pbarnard@Office-Mac-Pro-3 ConnectStats %

**Comment by roznet** [comment]
Weird. pod install says complete... if you try

xcodebuild -sdk iphonesimulator -workspace ConnectStats.xcworkspace -scheme ConnectStats -destination 'platform=iOS Simulator,name=iPhone 11' build CODE_SIGNING_REQUIRED=NO

from the connectstats directory, do you get an error? (this is the command the continuous integration runs to compile.

**Comment by paulrbarnard** [comment]
Brice,

Sorry for the delay.  My day job got in the way.

That build succeeded

I’ve got an urgent day job task to attend to for about 30 minutes but will lokk in a little more detail after that.

Thanks

Paul

**Comment by paulrbarnard** [comment]
Brice,

Cleared the NMI from my boss…

XCode build still fails after the successful build from the command line.  Just incase it was a problem I introduce I blew away the entire folder and cloned from GitHub again.  Same situation with the GenericJSON not found.  
I am running the latest XCode Beta so repeated the exercise with the 11.5 released version and yet again same situation. 

Don’t worry too much about this on my behalf as it is just for.a learning exercise to get me going on your fit-sdk-swift framework.   I can just dive into the code to pull out what i need rather than running and inspecting files etc.

More than happy to spend time debugging with you if you want to close off what it is.

Paul

**Comment by roznet** [comment]
This is weird. I have used the Xcode beta without issue. If the command line build works it means at some level it has all the files required.

When you open the workspace do you see the pods project correctly below the connectstats project?Also which target/device do you select to build? 

I am keen to make sure the app compiles for people so happy to help get to bottom of this. In your case by the way if all you want to look at is the fit swift sdk in that project there is a basic demo iOS app hopefully that compiles (no pod dependency)

**Comment by roznet** [comment]
By the way, can you double checked you opened the workspace not the project? in the terminal type `open ConnectStats.xcworkspace`

If I open the `xcodeproject` (that does not contains the pod dependencies) instead of the workspace  I get exactly the same error on No Such module 'GenericJSON' you mention above...

**Comment by paulrbarnard** [comment]
Brice,

I’ll check in the morning. It sounds highly likely...

Paul

**Comment by paulrbarnard** [comment]
Now I feel stupid.  Yes I had opened the project not the workspace.

It’s working fine now.

Many thanks for checking this.

Paul

**Comment by roznet** [comment]
Great to hear. 
I'll close the issue, let me know if you have any other questions on the code.

**Comment by paulrbarnard** [comment]
Brice,

Once again thanks.

I’ve built the FitFileExplorer and it is just what I was looking for to help visualise the file content and to get to grips with the library.  

I can now get to work on my FIT fixer app.  

For interest, below is what RideWithGPS does in long tunnels.  Each of those discontinuities is a long tunnel, several hundred meters not 20km...  Strava doesn’t let you cut anything out of the middle of a ride so I finish up with three separate ride logs after cutting and trimming.  No problem with that in general but if I’m trying to get a Fondo badge I need a continuous ride to qualify.  My only recourse was to export to GPX then edit in an editor before re-uploading.  That is not a lot of fun 
I’ve had other issues with missing heart rate in RideWithGPS and have had to use gotoes to merge the heart rate data from my apple watch with the record from RideWithGPS.  All in all a bit of a faff.  
I’ll probably just make it quick and dirty for my own use but might make an app out of it.  The last app I put on the AppStore was back in 2013, which is when I found out people don’t RTFM or use the Help.  A bit like me this time :-).  I’ll let you know if I publish an app and will give you full credit for the excellent framework for FIT if i do.

Paul

**Comment by roznet** [comment]
Interesting. 

The fit framework currently does not let your write back the fit file after changes. I always had in mind to do it, but never got the use case. If you want we can work on that in the library & app together. I will look over the weekend to refresh myself of how I was planning to add the write back to file..

FitFileExplorer is open source and free on the store (not planning to change that). It was more intended as a tool for myself as I need to debug/investigate things in the fit files while working on connectstats...

**Comment by paulrbarnard** [comment]
Brice,

I would certainly appreciate any help/pointers you can give on writing back the data.  I saw that the SDK has an encode module but having only grabbed your framework yesterday I hadn’t noticed the encode part was not their yet. Implementing that myself is probably beyond my capability.  I’m actually an embedded SW guy working in automotive so the highly abstracted and multi threaded realm of ios and macos is a bit outside my comfort zone.  On top of that I am trying to convert my head from ObjectiveC to Swift at the same time so using this task as a bit of a learning activity.  

Paul
