### ISSUE TITLE
Allow full offline mode by storing sent fit files in database

### ISSUE THREAD

**Issue by thaihugo** [roznet/connectstats#71]
Hi,

First let me thank you for your great program. It offers a great way to visualize data.

The recent incident with Garmin has me trying to get information directly from my fit files, downloaded from the watch and sent to the app using the IOS share function. This is perfectly working, but the fit file is only temporary. It will not be kept in database and no global statistics will be derived from it. It will also disappear if you import more fit files, and reimporting the same fit file will create a duplicate in the inbox document folder of the app.

I don't know if this is a wanted functionality, but in this days where we struggle to keep our data even partly offline, I think this would be an excellent function for your app to import a local fit folder or just to register a fit file send by the "send to" ios function in the database and get full history as if it was received from a connected garmin connect account.

I understand you already do offline if we connect to garmin first, but I'm not getting any data if I never connected, and I'm not sure I would get the same with a first import then a "send to" to add a subsequent fit file from my watch files.

Thanks for reading and considering this.

Hugo

**Comment by roznet** [comment]
Hi
Thanks for the suggestion. It is a good idea in current outage, and actually would be quite easy. At the time I implemented the functionality to open a fit file, I had to do something special to make it temporary... Would be easy to make it behave the same as when a fit file is received from the cloud. 

I'll make the change, maybe with an option so people can choose is the manual import is temporary or permanent...

**Comment by thaihugo** [comment]
That would be great. Thanks!

**Comment by roznet** [comment]
I made the change, so you can airdrop a fit file and it will register the activity permanently. I was about to make a release, so I stopped it and added the change, so hopefully if apple approves quickly will be released soon.

I'll make a change later to have the option to make it permanent or temporary, but for now in case the garmin outage continues for a while, this gives a way to update connectstats manually.

**Comment by roznet** [comment]
Won't enhance offline further. garmin service working
