### ISSUE TITLE
Truncated display

### ISSUE THREAD

**Issue by CharlesMagnuson** [roznet/connectstats#82]
After recently upgrading to v3.2 (3.2.0), I noticed a couple issues which are beginning to plague me:

1) The drop down menus in the bar that runs across the top of the application are truncated. While the menus are still selectable, I cannot discern what field I am modifying given the truncation.

2) Every time I open a FIT file, the columns are unhelpfully resized to a ridiculous configuration. The first column is so wide that I have to horizontally expand the application in order to resize the subsequent columns displayed. This problem is really slowing down my ability to use this application since I have to do so much dragging using my mouse to resize the UI to the correct proportions.

I have recorded a screencast which illustrates these two issues: https://youtu.be/5kkE2pjaQWs

I am using MacOS 10.15.7

**Comment by roznet** [comment]
Thanks for this. Yes looks bad and definitely doesn't behave like this on Big Sur. I don't have a Mac with Catalina unfortunately, so I can't test it. Do you have ability to run the latest built of that app? I am looking through google and will try to make a few adjustment to the storyboard, but I am not yet sure how I could test it.

**Comment by CharlesMagnuson** [comment]
Hello Roznet,

I apologize for taking so long to get back to you. At first our company was not permitting us to upgrade to Big Sur, but I just got around to performing that task on Friday and only then was I able to upgrade to the most recent version of FitFileExplorer. The new version of the app looks beautiful and works great, so my issue is resolved. Thank you for looking into this!
