### ISSUE TITLE
Swip through diagrams

### ISSUE THREAD

**Issue by Icebird2000** [roznet/connectstats#87]
On the activities details page you can swipe left right through the diagrams. But if you select one lap, you can only swipe left but not right. 
But at this time i don’t understand the main difference between tip and swipe and why they work differently. Swipe skip subdiagrams for example - swipe left from speed to puls, but if you tap on speed it shows some different diagrams for speed. 
It possible better to make a long press to select the wanted diagrams per hover dropdown.

**Comment by roznet** [comment]
Thanks for the comment. Yes, the swipe right was somehow missing for the lap, I added it for next version.

The idea is swipe left/right goes to next field (hr/speed/etc) and tap goes for one field  to different configuration.

I agree a configuration choice screen is better, didn't get around to that, I need to do something similar to what I put one for the stats screen (long press on icon on the right)

**Comment by roznet** [comment]
included in 6.8
